services:
  - type: web
    name: restaurante-el-punto
    env: python
    runtime: python-3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
