"""Agregar campo descripcion a DetallePedido

Revision ID: 0278e77895e8
Revises: 18303641a0ad
Create Date: 2025-06-18 10:02:25.893006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0278e77895e8'
down_revision = '18303641a0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
