"""Agregar campo guardado a CierreCaja

Revision ID: 18303641a0ad
Revises: ca2a9259833b
Create Date: 2025-06-17 12:16:47.536674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18303641a0ad'
down_revision = 'ca2a9259833b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_caja', schema=None) as batch_op:
        batch_op.drop_column('guardado')

    # ### end Alembic commands ###
