"""Agregar tabla CierreCaja

Revision ID: 2bdb054deb32
Revises: aff480699dc3
Create Date: 2025-05-29 19:40:48.058558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdb054deb32'
down_revision = 'aff480699dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('total_ventas', sa.Integer(), nullable=True),
    sa.Column('total_efectivo', sa.Integer(), nullable=True),
    sa.Column('total_fiado', sa.Integer(), nullable=True),
    sa.Column('pedidos_facturados', sa.Integer(), nullable=True),
    sa.Column('pedidos_pendientes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cierre_caja')
    # ### end Alembic commands ###
