"""Detecta cambios reales

Revision ID: 2eae2c22b052
Revises: 3a75e853beb3
Create Date: 2025-06-11 13:25:53.563104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eae2c22b052'
down_revision = '3a75e853beb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_detalles_pedido')
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_detalles_pedido_producto_id', 'producto', ['producto_id'], ['id'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pago', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fecha_pago')

    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_detalles_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('producto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_detalles_pedido_producto')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
