"""Agregar campo estado_pago a Pedido

Revision ID: 52e32f84a401
Revises: 53b961786fe0
Create Date: 2025-05-30 11:44:47.757596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e32f84a401'
down_revision = '53b961786fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('detalles_pedido')
    op.drop_table('cierre_caja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre_caja',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('total_ventas', sa.NUMERIC(), nullable=True),
    sa.Column('total_efectivo', sa.NUMERIC(), nullable=True),
    sa.Column('total_fiado', sa.INTEGER(), nullable=True),
    sa.Column('pedidos_facturados', sa.INTEGER(), nullable=True),
    sa.Column('pedidos_pendientes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), nullable=False),
    sa.Column('producto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mesa', sa.VARCHAR(length=10), nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cliente_nombre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cliente_telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cliente_direccion', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
