"""Corrección de import y cambios de modelo

Revision ID: 53b961786fe0
Revises: 2bdb054deb32
Create Date: 2025-05-29 21:26:13.705027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b961786fe0'
down_revision = '2bdb054deb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_caja', schema=None) as batch_op:
        batch_op.alter_column('total_ventas',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('total_efectivo',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cierre_caja', schema=None) as batch_op:
        batch_op.alter_column('total_efectivo',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('total_ventas',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
