"""Crear tabla pedidos

Revision ID: a300ce51baf3
Revises: 52e32f84a401
Create Date: 2025-05-30 12:26:23.291073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a300ce51baf3'
down_revision = '52e32f84a401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierre_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('total_ventas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_fiado', sa.Integer(), nullable=True),
    sa.Column('pedidos_facturados', sa.Integer(), nullable=True),
    sa.Column('pedidos_pendientes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('mesa', sa.String(length=10), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('cliente_direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_pedido')
    op.drop_table('pedidos')
    op.drop_table('cierre_caja')
    # ### end Alembic commands ###
