"""Agrega columna tipo a Pedido

Revision ID: aff480699dc3
Revises: 
Create Date: 2025-05-29 11:00:54.584914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff480699dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_pedido_domicilio')
    op.drop_table('pedidos_domicilios')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cliente_telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cliente_direccion', sa.String(length=200), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('mesa',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('mesa',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('cliente_direccion')
        batch_op.drop_column('cliente_telefono')
        batch_op.drop_column('cliente_nombre')
        batch_op.drop_column('tipo')

    op.create_table('pedidos_domicilios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cliente_nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cliente_telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cliente_direccion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_pedido_domicilio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pedido_domicilio_id', sa.INTEGER(), nullable=False),
    sa.Column('producto', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_domicilio_id'], ['pedidos_domicilios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
