"""Agregar tabla Categoria y relación con Producto

Revision ID: be36de94802f
Revises: 4560beb94a68
Create Date: 2025-05-30 16:51:38.012350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be36de94802f'
down_revision = '4560beb94a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('producto')
    op.drop_table('categoria')
    # ### end Alembic commands ###
