"""Agregar producto_id a DetallePedido

Revision ID: cd8c745d7b3c
Revises: be36de94802f
Create Date: 2025-06-02 14:41:44.723061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8c745d7b3c'
down_revision = 'be36de94802f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_detalles_producto_id', 'producto', ['producto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_detalles_producto_id', type_='foreignkey')
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###
